### ISSUE TITLE
eggdrop Won't start

### ISSUE THREAD

**Issue by DjLaz** [eelcohn/SynoDrop#9]
hello i installed egdrop on my synology Ds411j and it won't start do you have any sollution ? thanks

**Comment by eelcohn** [comment]
Hi, thanks for contacting me. Can you try the following?
* Remove the eggdrop package
* Reinstall the package
* Try to start the package
* Post the contents of the '/tmp/eggdrop-sss.log' file (you can view/retrieve it by SSH-ing into your disk station

Also, can you let me know what DSM version your diskstation is running? Thank you.

**Comment by DjLaz** [comment]
https://pastebin.com/yJqvAxEY
i'm on ds411j running on Version: 6.2.2-24922-3 version 
i did all that you said before and didn't work at all

**Comment by DjLaz** [comment]
Sun Oct 20 15:07:51 2019: Creating new conf file /var/packages/eggdrop/etc/eggdrop.conf
Sun Oct 20 15:08:16 2019: Starting Eggdrop...
Sun Oct 20 15:08:16 2019: Creating new user file /var/packages/eggdrop/etc/eggdrop.user
./eggdrop: error while loading shared libraries: libtcl.so: cannot open shared object file: No such file or directory
Sun Oct 20 15:08:21 2019: Cannot stop Eggdrop. Eggdrop is not running.
Sun Oct 20 15:18:13 2019: Starting Eggdrop...
Sun Oct 20 15:18:13 2019: Creating new user file /var/packages/eggdrop/etc/eggdrop.user
./eggdrop: error while loading shared libraries: libtcl.so: cannot open shared object file: No such file or directory
Sun Oct 20 15:18:17 2019: Cannot stop Eggdrop. Eggdrop is not running.
Sun Oct 20 16:17:46 2019: Starting Eggdrop...
Sun Oct 20 16:17:46 2019: Creating new user file /var/packages/eggdrop/etc/eggdrop.user
./eggdrop: error while loading shared libraries: libtcl.so: cannot open shared object file: No such file or directory
Sun Oct 20 16:17:49 2019: Cannot stop Eggdrop. Eggdrop is not running.
Mon Oct 21 01:32:55 2019: Starting Eggdrop...
Mon Oct 21 01:32:55 2019: Creating new user file /var/packages/eggdrop/etc/eggdrop.user
./eggdrop: error while loading shared libraries: libtcl.so: cannot open shared object file: No such file or directory
Mon Oct 21 01:32:58 2019: Cannot stop Eggdrop. Eggdrop is not running.
Mon Oct 21 01:40:33 2019: Starting Eggdrop...
Mon Oct 21 01:40:33 2019: Creating new user file /var/packages/eggdrop/etc/eggdrop.user
./eggdrop: error while loading shared libraries: libtcl.so: cannot open shared object file: No such file or directory
Mon Oct 21 01:40:36 2019: Cannot stop Eggdrop. Eggdrop is not running.

**Comment by eelcohn** [comment]
Okay, it seems that eggdrop can't find the tcl library. What Tcl package have you installed?

**Comment by DjLaz** [comment]
yours and after that the update on synocommunity

**Comment by eelcohn** [comment]
Thank you, you just found a bug in the package. When the Tcl package was integrated into SynoCommunity, the link to the libtcl.so file was slightly altered. This is now the cause of your problem.

I need to run some tests and probably publish a new version of the Eggdrop package which links to the correct file. I hope to be able to do this within one day. I'll get back to you.

**Comment by eelcohn** [comment]
Okay, so a quick solution for this issue would be to ssh into your DiskStation and do:
```
$ sudo mkdir -p /usr/local/lib
$ sudo ln -s /var/packages/tcl/lib/libtcl8.6.so /usr/local/lib/libtcl.so
```
This will create a symlink to the Tcl library in /usr/local/lib so that eggdrop can find it. The `mkdir` will create the lib directory if it doesn't exist (it probably won't exist on DiskStations which never had DSM6.1 or lower installed).

I'll incorporate the correct path to the Tcl library in a new version of the Eggdrop v1.8.4 package. When that package is installed it should permanently fix this issue, and the quickfix can be removed.

**Comment by DjLaz** [comment]
do i have to reinstall it cause didn't work also with the commande?

**Comment by DjLaz** [comment]
do you have the commande line to install package ? i have debian

**Comment by DjLaz** [comment]
any news? didn't work at all thanks

**Comment by eelcohn** [comment]
Hi,
Sorry for the late response, I've been busy with offline stuff :-)
I've recompiled eggdrop with a reference to the correct libtcl.so file. Can you try this?:
1. Remove the eggdrop package
2. Remove the Tcl package
3. Re-install a fresh copy of the Tcl package from the SynoCommunity
4. Install the new [eggdrop package from this pre-release](https://github.com/eelcohn/SynoDrop/releases/download/v1.8.4-2/eggdrop_88f6281-6.1_1.8.4-2.spk)

**Comment by DjLaz** [comment]
work like a charme  thanks a lot 
question where are the files of the egg and can i move them ? if yes how ?
i want to put some tcl on it but it's hard for me to do it through the ssh

**Comment by eelcohn** [comment]
That's nice to hear.

The default location for the config files is:
`/var/packages/eggdrop/etc/`

There are several ways to use different locations for the config file:
1. Move the `eggdrop.conf` file to a new location, e.g. `/volume1/eggshare/eggdrop.conf` and create a new file `/var/packages/eggdrop/etc/eggdrop.conf` which just contains one line: `source /volume1/eggshare/eggdrop.conf`. In this example you moved the config file to a network share called 'eggshare'
2. Create a symlink to a new location (e.g. network share) by doing `ln -s /volume1/eggshare /var/packages/eggdrop/etc/eggshare` and edit the `eggdrop.conf` file accordingly
The backup integration with HyperBackup might break when using symlinks though. Please let me know if you have verified that it does or does not break that :-)

FYI:
Certificates for eggdrop are stored by default in `/var/packages/eggdrop/etc/cert/` and log files are stored by default in `/var/packages/eggdrop/etc/logs/`

**Comment by DjLaz** [comment]
is there something wrong on the second way ?
the symlink you create is on the bot folder

**Comment by DjLaz** [comment]
sorry but the symlik doesb't work for me i can't open it cause i'm on admin userand not root
